### ISSUE TITLE
Bit Shift Instructions

### ISSUE THREAD

**Issue by AnnsAnns** [HAW-Rust-SoSe24/gb_emulator#5]
https://rgbds.gbdev.io/docs/v0.6.1/gbz80.7/#Bit_Operations_Instructions

**Comment by LaurinZ** [comment]
doing Bit operations for now, bit shifts and bit operations maybe could be/have been seperated?
https://github.com/HAW-Rust-SoSe24/gb_emulator/tree/bit_operations
